---
title: "Practical 3"
author: "Kgotso Modise"
date: "20 February 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

matrix_vals <- c(0, 0.2, 0.5, 0.3, 0.45, 0.2, 0.1, 0.25, 0, 1, 0, 0, 0, 0, 0, 1);


p = matrix(matrix_vals, nrow = 4, ncol = 4, byrow = T)

for(i in 1:nrow(p))
{
  for(j in 1:ncol(p))
  {
    if(p[i, j] != 0 && p[j, i] != 0)
    {
      cat("State ", i, " communicates with state ", j, "\n")
    }
    else if(p[i, j] != 0)
    {
      cat("State ", j, " is accessible from state", i, "\n")
    }
  }
}

```

```{r}
#Finding n
found_n <- F
n <- 1
pn = p
#Finding minimum n
while(!found_n)
{
  
  for(i in 1:nrow(p))
  {
    #Finding n
    if(pn[i, i] != 0)
    {
      found_n <- T
    }
    else
    {
      found_n <- F
      n <-  n + 1
      pn = pn%*%p
      break
    }
  }
}
cat("Minimum n required is ", n)

#Finding the period of each state
i = 1
ns <- matrix(0, ncol = 4, nrow = 4)
periods <- matrix(0, ncol = 3, nrow = 4)
for(i in 1:ncol(p))
{
  pn = p
  found_4 <- 0
  j = 1
  n = 1
  
  if(p[i, i] > 0)
  {
      ns[i, j] <- n
      j = 2
      n = 2
      found_4 <- 1
  }
  while(found_4 < 4)
  {
    if(pn[i, i] > 0)
    {
      found_4 = found_4 + 1
      ns[i, j] <- n
      j = j + 1
      
    }
    n = n + 1
    pn = pn%*%p;
    for(k in 1:3)
    {
      periods[i, k] = ns[i, k + 1] - ns[i, k]
    }
    common = periods[i, 1]
    is_period = T
    for(k in 1:3)
    {
      if(periods[i, k] == common && common != 0) is_period = T
      else is_period = F
    }
    if(is_period) cat("The period for state ", i, " is ", common, "\n")
  }
  
}
print(ns)


#Finding the period of each state
```

```{r}

vals <- c(0.15,0.85,0,0,0,0,0,0,0,0,0.1,0.4,0.5,0,0,0,0,0,0,0,0,0.25,0.5,0.25,0,0,0,0,0,0,0,0,0.3,0.4,0.3,0,0,0,0,0,0,0,0,0.5,0.2,0.3,0,0,0,0,0,0,0,0,0.45,0.25,0.3,0,0,0,0,0,0,0,0,0.5,0.3,0.2,0,0,0,0,0,0,0,0,0.7,0.2,0.1,0,0,0,0,0,0,0,0,0.75,0.05,0.2,0,0,0,0,0,0,0,0,0.05,0.95)

P <- matrix(vals, nrow = 10, ncol = 10, byrow = T)


n  = 2
has_zero = T
PN = P

while(has_zero)
{
  PN = PN%*%P
  for(i in 1:nrow(P))
    for(j in 1:ncol(P))
    {
      if(PN[i, j] == 0)
      {
        has_zero = T
        break;
      }
      else has_zero = F
    }
  if(!has_zero)
  {
    cat("Required number N is ", n, "\n")
    print(PN)
    break;
  }
  n = n + 1
}

```

